version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: my_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  palindrome-app:
      image: cme/palindrome-app
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: my_db
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: postgres
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 5432:5432
      depends_on:
        - postgres
