{{- if .Values.startupScripts }}
{{- $highAvailability := gt (int .Values.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palindrome-app.fullname" . }}-startup
  labels:
    {{- include "palindrome-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.startupScripts }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
