---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "palindrome-app.fullname" . }}
  labels:
    {{- include "palindrome-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - name: http
      port: {{.Values.service.httpPort}}
      targetPort: {{.Values.service.httpPort}}
      protocol: TCP
  selector:
    {{- include "palindrome-app.selectorLabels" . | nindent 4 }}
